package:
  name: marbel
  version: "0.1.0"

source:
  path: /home/tlin/Projects/marbel
  #  git_url: https://github.com/jlab/marbel
  #   git_rev: dev  # <-- use 'dev' instead of '0.1.0'

requirements:
  build:
    - python
    - hatchling

  run:
    - python
    - arviz
    - pymc
    - typer
    - biopython
    - pyarrow
    - typing-extensions
    - pandas
    - ete4  
    - progress
    - joblib
    - polars
    - insilicoseq-marbel 

test:
  imports:
    - marbel
  commands:
    - marbel --help

about:
  home: https://github.com/jlab/marbel
  license: Apache-2.0

