name: marbel
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - flake8
  - python >= 3.10
  - pytest
  - pytest-cov
  - biopython
  - coverage >= 6  # to ensure lcov option is available
  - pip:
    - pynose
    - ./
