package:
  name: marbel
  version: 0.0.1

source:
  path: .

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - hatchling
    - hatch-requirements-txt

  run:
    - python
    - bioconda::bioconductor-polyester=1.24.0 
    - numpy
    - pandas

about:
  home: https://github.com/jlab/marbel
  license: Apache-2.0
  summary: "A CLI for creating a simulated metatranscriptome dataset"


channels:
  - defaults
  - conda-forge
  - bioconda